import {
  Activity,
  BadgeCheck,
  Boxes,
  CircleHelp,
  ClipboardList,
  Filter,
  Gauge,
  HardDrive,
  Home,
  LifeBuoy,
  Megaphone,
  Menu,
  Package,
  PlayCircle,
  Users,
  Wallet,
  Wrench,
  Palette,
  Sparkles,
  type LucideIcon,
} from "lucide-react";
import type { ClaveIcono } from "@/lib/navegacion";

export const ICONOS_MENU: Record<ClaveIcono, LucideIcon> = {
  embudo: Filter,
  midia: Home,
  tablero: Gauge,
  aprobaciones: BadgeCheck,
  informes: ClipboardList,
  contactos: Users,
  ventas: Package,
  cobranzas: Wallet,
  casos: LifeBuoy,
  services: Wrench,
  equipos: HardDrive,
  stock: Boxes,
  movimientos: Activity,
  marketing: Megaphone,
  pedidos_material: Palette,
  videos: PlayCircle,
  guia: CircleHelp,
  asistente: Sparkles,
  mas: Menu,
};
